import { CompanyData, Block } from "../types";

export function displayName(c: CompanyData): string {
  if (c.brandName && c.brandName !== c.legalName) {
    return `${c.legalName} ("${c.brandName}")`;
  }
  return c.legalName || "[Company Legal Name]";
}

export function shortName(c: CompanyData): string {
  return c.brandName || c.legalName || "the Company";
}

export function fullAddress(c: CompanyData): string {
  const parts = [c.address, c.city, c.state, c.pincode].filter(Boolean);
  return parts.length ? parts.join(", ") : "[Registered Office Address]";
}

export function regLine(c: CompanyData): string {
  const idLabel = c.entityType.includes("LLP") ? "LLPIN" : "CIN / Registration No.";
  const id = c.cin || "[__________]";
  return `${displayName(c)}, a ${c.entityType} incorporated under the laws of India, bearing ${idLabel} ${id}, having its registered office at ${fullAddress(c)} (hereinafter referred to as the "Company").`;
}

export function todayLong(): string {
  return new Date().toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

export function governingLaw(c: CompanyData): Block[] {
  const state = c.state || "Karnataka";
  const seat = c.city || "[City]";
  return [
    { type: "h2", text: "Governing Law & Jurisdiction" },
    {
      type: "p",
      text: `This document shall be governed by and construed in accordance with the laws of India. The courts at ${seat}, ${state} shall have exclusive jurisdiction over any dispute arising out of or in connection with this document, subject to the dispute-resolution provisions below.`,
    },
    {
      type: "p",
      text: `Any dispute, controversy or claim arising out of or relating to this document shall, as far as possible, be settled amicably. Failing amicable settlement within thirty (30) days, the dispute shall be referred to arbitration by a sole arbitrator under the Arbitration and Conciliation Act, 1996. The seat and venue of arbitration shall be ${seat}, ${state}, and the proceedings shall be conducted in English.`,
    },
  ];
}

export const DISCLAIMER =
  "This document is a customisable template generated by Hyroo for general informational purposes only and does not constitute legal advice. Laws and stamp-duty requirements vary by state and change over time. Please have it reviewed by a qualified advocate and executed on appropriate stamp paper / e-stamp before relying on it.";

export function disclaimer(): Block {
  return { type: "note", text: DISCLAIMER };
}

export function signCompanyEmployee(c: CompanyData, otherLabel = "Employee"): Block {
  return {
    type: "sign",
    left: [
      `For and on behalf of ${shortName(c)}`,
      "",
      "_______________________",
      c.signatoryName || "[Authorised Signatory]",
      c.signatoryDesignation || "[Designation]",
      `Date: ${todayLong()}`,
    ],
    right: [
      `Accepted by ${otherLabel}`,
      "",
      "_______________________",
      "Name: __________________",
      "Date: __________________",
      "Place: _________________",
    ],
  };
}
